apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cicd-demo
  name: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cicd-demo
    spec:
      containers:
      - image: brinendamketum/gitopsimage:16
        name: nodejs
        resources: {}
status: {}
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: lb-service
#   labels:
#     app: lb-service
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 5000
#   selector:
#     app: flaskdemo
